version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002
  electionDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    ports:
      - 3307:3306
  electionDBMigration:
    image: electiondbmigration
    environment:
      - DATABASE_URL=electionDB
    depends_on:
      electionDB:
        condition: service_healthy
  admin:
    image: admin
    environment:
      - DATABASE_URL=electionDB
      - TZ=Europe/Belgrade
    depends_on:
      - electionDBMigration
      - authenticationDBMigration
    ports:
      - 5001:5001
  dameon:
    image: dameon
    environment:
      - DATABASE_URL=electionDB
      - TZ=Europe/Belgrade
    depends_on:
      - electionDBMigration
  voting:
    image: voting
    environment:
      - DATABASE_URL=electionDB
    depends_on:
      - electionDBMigration
      - authenticationDBMigration
    ports:
      - 5003:5003
  adminer:
    image: adminer
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379